apiVersion: v1
kind: Pod
metadata:
  name: broken-pod5
spec:
  containers:
    - name: busybox
      image: busybox
      command:
        - sleep
        - "3600"
      volumeMounts:
        - name: secret-volume
          mountPath: "/etc/simple-secret"
  volumes:
    - name: secret-volume
      secret:
        secretName: secret-doesntexist
