apiVersion: v1
kind: Pod
metadata:
  name: broken-pod6
spec:
  containers:
    - name: stress
      image: polinux/stress
      resources:
        limits:
          memory: 100Mi
        requests:
          memory: 50Mi
      command: ["stress"]
      args: ["--vm", "1", "--vm-bytes", "250M", "--vm-hang", "1"]
