apiVersion: v1
kind: Pod
metadata:
  name: broken-pod7
spec:
  containers:
    - name: busybox
      image: busybox
      command:
        - sleep
        - "3600"
      resources:
        requests:
          memory: 100Gi
