apiVersion: v1
kind: Service
metadata:
  name: broken-service2
spec:
  ports:
    - port: 80
  selector:
    apps: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: broken-service-wrong-selector
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80
